[font]
	size = 18
	[font.normal]
	family = "terminus"
	style = "regular"

	[font.bold]
	family = "terminus"
	style = "regular"

	[font.italic]
	family = "terminus"
	style = "italic"

[scrolling]
history = 2_000

# Keybind to open new instance with the same working dir
[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

# This is gruvbox-material-hard-dark
[colors.primary]
#background = '#1d2021'
background = '#000000'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
