[font]
	size = 18
	[font.normal]
	family = "terminus"
	style = "regular"

	[font.bold]
	family = "terminus"
	style = "bold"

	[font.italic]
	family = "terminus"
	style = "italic"

[scrolling]
history = 2_000

# Keybind to open new instance with the same working dir
[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[colors.primary]
foreground = "#e0def4"
background = "#414141"

