[font]
	size = 19
	[font.normal]
	family = "terminus"
	style = "regular"

	[font.bold]
	family = "terminus"
	style = "regular"

	[font.italic]
	family = "terminus"
	style = "italic"

# need this to handle neovim's column line without having to resize
[window.dimensions]
columns = 90
lines   = 25

[scrolling]
history = 2_000

# Keybind to open new instance with the same working dir
[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
#
[colors.primary]
background = "0x1d4444"
foreground = "0xfeeecf"
