[font]
	size = 13
# 	[font.normal]
# 	family = "Terminus"
# 	style = "regular"
#
# 	[font.bold]
# 	family = "Terminus"
# 	style = "regular"
#
# 	[font.italic]
# 	family = "Terminus"
# 	style = "italic"

# need this to handle neovim's column line without having to resize
[window.dimensions]
columns = 90
lines   = 25

[scrolling]
history = 2_000

# Keybind to open new instance with the same working dir
[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[colors.primary]
#background = "0x1d2021"
background = "0x000000"
foreground = "0xd4be98"

[colors.normal]
black = "0x32302f"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"

[colors.bright]
black = "0x32302f"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"
