[font]
	size = 15
	[font.normal]
	family = "fira code"
	style = "regular"

	[font.bold]
	family = "fira code"
	style = "bold"

	[font.italic]
	family = "fira code"
	style = "italic"

[scrolling]
history = 4_000



# Keybind to open new instance with the same working dir
[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]


[colors.primary]
background = "0x1e2127"
foreground = "0xabb2bf"
bright_foreground = "0xe6efff"

[colors.normal]
black = "0x1e2127"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0x828791"

[colors.bright]
black = "0x5c6370"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0xe6efff"

[colors.dim]
black = "0x1e2127"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0x828791"

