[font]
	size = 18
	[font.normal]
	family = "terminus"
	style = "regular"

	[font.bold]
	family = "terminus"
	style = "regular"

	[font.italic]
	family = "terminus"
	style = "italic"

[scrolling]
history = 2_000

# Keybind to open new instance with the same working dir
[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
[colors]
  [colors.primary]
  background = "#4c4e52"
  foreground = "#ffffff"

  [colors.cursor]
  text = "#122637"
  cursor = "#f0cb09"

  [colors.normal]
  black = "#242424"
  red = "#f62b5a"
  green = "#47b413"
  yellow = "#e3c401"
  blue = "#24acd4"
  magenta = "#f2affd"
  cyan = "#13c299"
  white = "#e6e6e6"

  [colors.bright]
  black = "#616161"
  red = "#ff4d51"
  green = "#35d450" 
  yellow = "#e9e836"
  blue = "#5dc5f8"
  magenta = "#feabf2"
  cyan = "#24dfc4"
  white = "#ffffff"

